### ISSUE TITLE
while true

### ISSUE THREAD

**Issue by casa7x** [AnnLuschik/lesson-16-s#1]
https://github.com/AnnLuschik/lesson-16-s/blob/0a6d40f740e09dd1ba9f486af62daff2e3dc99e2/task1.js#L10

while true это некий хак такой, его не обязательно использовать постоянно, и здесь не обзяательно, но введёт пользователь не то что, тебе нужно, один раз скажешь ему и всё. Постоянно заставлять, пользователя вводить данные тоже не есть хорошо и не очень юзер френдли

**Comment by AnnLuschik** [comment]
Исправлено.
